name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    uses: VitifyCode/VitifyCode-CI/.github/workflows/gt-ci.yml@main
    with:
      baseline-name: 'GtoolkitAcp'
      test-suite-name: 'GToolkit-ACP Tests'
    secrets: inherit
